{% set name = "python-nubia" %}
{% set version = "0.2b5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 051931c7a67bbfef9e30ba5b08fa96b35d699621ac0c0030e069caa2475456bd

build:
  number: 0
  entry_points:
    - _nubia_complete = nubia_complete.main:main
  disable_pip: True
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  host:
    - python
    - setuptools
    - dataclasses
    - jellyfish
    - prettytable
    - prompt-toolkit >=2
    - pygments
    - pyparsing >=2.2.0
    - termcolor
    - wcwidth
    - nose >=1.0
    - coverage
    - typing_inspect
  run:
    - python
    - setuptools
    - dataclasses
    - jellyfish
    - prettytable
    - prompt-toolkit >=2
    - pygments
    - pyparsing >=2.2.0
    - termcolor
    - wcwidth
    - typing_inspect

test:
  imports:
    - nubia
    - nubia.internal
    - nubia.internal.commands
    - nubia.internal.io
    - nubia.internal.typing
    - nubia.internal.ui
    - nubia_complete
  commands:
    - _nubia_complete --help

about:
  home: "https://github.com/facebookincubator/python-nubia"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "A framework for building beautiful shells"
  doc_url: "https://github.com/facebookincubator/python-nubia"
  dev_url: "https://github.com/facebookincubator/python-nubia"

extra:
  recipe-maintainers:
    - ph20
