{% set name = "pycurl" %}
{% set version = "7.43.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 43231bf2bafde923a6d9bb79e2407342a5f3382c1ef0a3b2e491c6a4e50b91aa

build:
  number: 0
  disable_pip: True
  detect_binary_files_with_prefix: false
  script: "{{ PYTHON }} setup.py install --curl-config=$PREFIX/bin/curl-config --openssl-dir=$PREFIX --record record.txt"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - libcurl
    - openssl
  run:
    - python

test:
    imports:
        - curl
        - pycurl
about:
  home: http://pycurl.sourceforge.net/
  license: LGPL, MIT
  license_file: COPYING-LGPL
  license_family: LGPL
  summary: A Python Interface To The cURL library
  description: |
    PycURL is a Python interface to libcurl, the multiprotocol file transfer library.
    Similarly to the urllib Python module, PycURL can be used to fetch objects identified
    by a URL from a Python program.
  doc_url: http://pycurl.io/docs/latest/index.html
  doc_source_url: https://github.com/pycurl/pycurl/blob/master/doc/index.rst
  dev_url: https://github.com/pycurl/pycurl
extra:
  recipe-maintainers:
    - ph20
