{% set name = "pytils" %}
{% set version = "0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1e85118d095d48928fef1a73e3e1dccdbc07bc931131705976b7dd05b66627fc

build:
  number: 1
  disable_pip: True

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - pytils
    - pytils.templatetags
    - pytils.test
    - pytils.test.templatetags
    - pytils.third

about:
  home: https://github.com/j2a/pytils/
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: 'Russian-specific string utils'
  doc_url: https://github.com/j2a/pytils/
  dev_url: https://github.com/j2a/pytils/

extra:
  recipe-maintainers:
    - ph20