package:
  name: user_agent
  version: 0.1.9

source:
  url: http://pypi.ph20.org.ua/simple/user_agent/user_agent-0.1.9.tar.gz
  sha256: 8f1ad46cc4aef9f99515ea1c74bb8cacc43e23074c335b2ba2db7735ebe9c0d5

build:
  number: 0
  disable_pip: True

requirements:
  build:
    - python      [linux]
  host:
    - python 3.6
    - setuptools
  run:
    - python 3.6
    - setuptools
    - wheel
    - six

test:
  commands:
    - ua -h
  imports:
    - user_agent

about:
  home: https://github.com/lorien/user_agent
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: User-Agent generator
  doc_url: https://github.com/lorien/user_agent
  dev_url: https://github.com/lorien/user_agent
